// Hand-rolled hooks for endpoints that aren't (yet) generated by Orval.
// These call the same `customFetch` mutator the orval client uses, so
// session cookies / base URL / error handling stay consistent. When
// these endpoints are eventually moved into openapi.yaml the hooks here
// can be replaced with the generated equivalents.

import { useMutation, useQuery } from "@tanstack/react-query";
import { customFetch } from "@workspace/api-client-react";

// ---------- Asset extension fields ----------

// Server includes these on every Asset payload; the orval-generated
// `Asset` type doesn't know about them yet, so we widen at the call
// site via this intersection.
export type AssetExt = {
  category: "TRUCK" | "TRAILER" | "HANDHELD" | "CUSTOM";
  customCategoryLabel: string | null;
  quantity: number;
  assignedCrewId: number | null;
  assignedCrewName: string | null;
  lastAssignedAt: string | null;
  lastAssignedByUserId: number | null;
  lastAssignedByName: string | null;
  // Trailers + quantity-tracked items report `usageUnit: "NONE"` and
  // a sentinel `usageUntilDue` value. UIs gate on usageUnit before
  // formatting the "X miles until due" string.
  usageUnit: "MILES" | "HOURS" | "NONE";
};

// ---------- Crews ----------
export type Crew = { id: number; name: string };
export type CrewMember = {
  userId: number;
  fullName: string;
  role: string;
  department: string;
};
export type CrewDetail = {
  id: number;
  name: string;
  members: CrewMember[];
  trucks: Array<{ id: number; name: string; status: string; slug: string | null }>;
  equipment: Array<{ id: number; name: string; type: string; status: string; slug: string | null }>;
};

const CREWS_KEY = ["crews"] as const;

export function useListCrews() {
  return useQuery({
    queryKey: CREWS_KEY,
    queryFn: () => customFetch<{ crews: Crew[] }>("/crews"),
  });
}

export function getCrewDetailKey(id: number) {
  return ["crew", id] as const;
}

export function useCrewDetail(id: number) {
  return useQuery({
    queryKey: getCrewDetailKey(id),
    queryFn: () => customFetch<{ crew: CrewDetail }>(`/crews/${id}`),
    enabled: id > 0,
  });
}

// ---------- Equipment Items ----------
export type EquipmentItem = {
  id: number;
  equipmentId: number;
  name: string;
  quantity: number;
  unit: string | null;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
};

export function getEquipmentItemsKey(equipmentId: number) {
  return ["equipment-items", equipmentId] as const;
}

export function useEquipmentItems(equipmentId: number) {
  return useQuery({
    queryKey: getEquipmentItemsKey(equipmentId),
    queryFn: () =>
      customFetch<{ items: EquipmentItem[] }>(`/equipment/${equipmentId}/items`),
    enabled: equipmentId > 0,
  });
}

export type CreateEquipmentItemBody = {
  name: string;
  quantity?: number;
  unit?: string;
  notes?: string;
};

export function useCreateEquipmentItem(equipmentId: number) {
  return useMutation({
    mutationFn: (body: CreateEquipmentItemBody) =>
      customFetch<{ item: EquipmentItem }>(`/equipment/${equipmentId}/items`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      }),
  });
}

export function useDeleteEquipmentItem(equipmentId: number) {
  return useMutation({
    mutationFn: (itemId: number) =>
      customFetch<{ ok: boolean }>(`/equipment/${equipmentId}/items/${itemId}`, {
        method: "DELETE",
      }),
  });
}

// ---------- Assignment ----------
export type AssignAssetBody = { crewId: number | null; note?: string };

export function useAssignAsset(slug: string) {
  return useMutation({
    mutationFn: (body: AssignAssetBody) =>
      customFetch<{ asset: unknown }>(`/assets/${encodeURIComponent(slug)}/assign`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      }),
  });
}

export type AssignmentHistoryEntry = {
  id: number;
  changedAt: string;
  oldCrewId: number | null;
  oldCrewName: string | null;
  newCrewId: number | null;
  newCrewName: string | null;
  changedByUserId: number | null;
  changedByName: string | null;
  note: string | null;
};

export function getAssignmentHistoryKey(slug: string) {
  return ["assignment-history", slug] as const;
}

export function useAssignmentHistory(slug: string) {
  return useQuery({
    queryKey: getAssignmentHistoryKey(slug),
    queryFn: () =>
      customFetch<{ history: AssignmentHistoryEntry[] }>(
        `/assets/${encodeURIComponent(slug)}/assignment-history`,
      ),
  });
}

// ---------- Create Truck ----------
export type CreateTruckBody = {
  name: string;
  vehicleType?: "TRUCK" | "TRAILER";
  brand?: string;
  model?: string;
  vin?: string;
  plate?: string;
  status?: string;
  departmentId: number;
  purchasePriceCents?: number;
  purchaseDate?: string;
  currentMileage?: number;
  serviceIntervalMiles?: number;
};

export function useCreateTruck() {
  return useMutation({
    mutationFn: (body: CreateTruckBody) =>
      customFetch<{ truck: unknown }>("/trucks", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ ...body, status: body.status ?? "ACTIVE" }),
      }),
  });
}

// ---------- Create Equipment ----------
export type CreateEquipmentBody = {
  name: string;
  type: string;
  category?: "HANDHELD" | "CUSTOM";
  customCategoryLabel?: string;
  quantity?: number;
  brand?: string;
  model?: string;
  serial?: string;
  status?: string;
  departmentId: number;
  purchasePriceCents?: number;
  purchaseDate?: string;
  currentHours?: number;
  serviceIntervalHours?: number;
};

export function useCreateEquipment() {
  return useMutation({
    mutationFn: (body: CreateEquipmentBody) =>
      customFetch<{ equipment: unknown }>("/equipment", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ ...body, status: body.status ?? "ACTIVE" }),
      }),
  });
}

// ---------- Create Crew ----------
export type CreateCrewBody = {
  name: string;
  leadUserId: number;
};

export function useCreateCrew() {
  return useMutation({
    mutationFn: (body: CreateCrewBody) =>
      customFetch<{ crew: { id: number; name: string } }>("/crews", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      }),
  });
}

// ---------- Accounting ----------
export type AccountingMonthRow = {
  month: string;
  collectedRevenueCents: number;
  maintenanceSpendCents: number;
};

export type AccountingBranch = {
  departmentId: number | null;
  departmentLabel: string;
  openInvoiceCents: number;
  collectedRevenueCents: number;
  quotePipelineCents: number;
  maintenanceSpendCents: number;
  monthly: AccountingMonthRow[];
};

export type AccountingSummary = {
  totals: {
    openInvoiceCents: number;
    collectedRevenueCents: number;
    quotePipelineCents: number;
    maintenanceSpendCents: number;
  };
  branches: AccountingBranch[];
  orgMonthly: AccountingMonthRow[];
};

export const ACCOUNTING_KEY = ["accounting", "summary"] as const;

export function useAccountingSummary() {
  return useQuery({
    queryKey: ACCOUNTING_KEY,
    queryFn: () => customFetch<AccountingSummary>("/accounting/summary"),
  });
}

