// Hand-rolled hooks for endpoints that aren't (yet) generated by Orval.
// These call the same `customFetch` mutator the orval client uses, so
// session cookies / base URL / error handling stay consistent. When
// these endpoints are eventually moved into openapi.yaml the hooks here
// can be replaced with the generated equivalents.

import { useMutation, useQuery } from "@tanstack/react-query";
import { customFetch } from "@workspace/api-client-react";

// ---------- Asset extension fields ----------

// Server includes these on every Asset payload; the orval-generated
// `Asset` type doesn't know about them yet, so we widen at the call
// site via this intersection.
export type AssetExt = {
  category: "TRUCK" | "TRAILER" | "HANDHELD" | "CUSTOM";
  customCategoryLabel: string | null;
  quantity: number;
  assignedCrewId: number | null;
  assignedCrewName: string | null;
  lastAssignedAt: string | null;
  lastAssignedByUserId: number | null;
  lastAssignedByName: string | null;
  // Trailers + quantity-tracked items report `usageUnit: "NONE"` and
  // a sentinel `usageUntilDue` value. UIs gate on usageUnit before
  // formatting the "X miles until due" string.
  usageUnit: "MILES" | "HOURS" | "NONE";
};

// ---------- Crews ----------
export type Crew = { id: number; name: string };

const CREWS_KEY = ["crews"] as const;

export function useListCrews() {
  return useQuery({
    queryKey: CREWS_KEY,
    queryFn: () => customFetch<{ crews: Crew[] }>("/crews"),
  });
}

// ---------- Assignment ----------
export type AssignAssetBody = { crewId: number | null; note?: string };

export function useAssignAsset(slug: string) {
  return useMutation({
    mutationFn: (body: AssignAssetBody) =>
      customFetch<{ asset: unknown }>(`/assets/${encodeURIComponent(slug)}/assign`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      }),
  });
}

export type AssignmentHistoryEntry = {
  id: number;
  changedAt: string;
  oldCrewId: number | null;
  oldCrewName: string | null;
  newCrewId: number | null;
  newCrewName: string | null;
  changedByUserId: number | null;
  changedByName: string | null;
  note: string | null;
};

export function getAssignmentHistoryKey(slug: string) {
  return ["assignment-history", slug] as const;
}

export function useAssignmentHistory(slug: string) {
  return useQuery({
    queryKey: getAssignmentHistoryKey(slug),
    queryFn: () =>
      customFetch<{ history: AssignmentHistoryEntry[] }>(
        `/assets/${encodeURIComponent(slug)}/assignment-history`,
      ),
  });
}

// ---------- Accounting ----------
export type AccountingMonthRow = {
  month: string;
  collectedRevenueCents: number;
  maintenanceSpendCents: number;
};

export type AccountingBranch = {
  departmentId: number | null;
  departmentLabel: string;
  openInvoiceCents: number;
  collectedRevenueCents: number;
  quotePipelineCents: number;
  maintenanceSpendCents: number;
  monthly: AccountingMonthRow[];
};

export type AccountingSummary = {
  totals: {
    openInvoiceCents: number;
    collectedRevenueCents: number;
    quotePipelineCents: number;
    maintenanceSpendCents: number;
  };
  branches: AccountingBranch[];
  orgMonthly: AccountingMonthRow[];
};

export const ACCOUNTING_KEY = ["accounting", "summary"] as const;

export function useAccountingSummary() {
  return useQuery({
    queryKey: ACCOUNTING_KEY,
    queryFn: () => customFetch<AccountingSummary>("/accounting/summary"),
  });
}

